### ISSUE TITLE
Option to upload demos

### ISSUE THREAD

**Issue by crashzk** [MoritzLoewenstein/AutoDemoUpload#1]
First of all, thanks for sharing this resource, which is really much appreciated by me.

From what I have seen so far, it sends the Demos to the server's FastDL, currently I have CSGO servers rented from a host. So far so good, but I wanted to set up the demos on my own website / web hosting, currently have this feature in the plugin? Do you want to implement it if you don't have one?

Again, thanks for sharing this resource!

**[EDIT1]**
Yes, you still need the extensions **CURL** and **BZIP2**, correct?http://forums.alliedmods.net/showthread.php?t=152216
http://forums.alliedmods.net/showthread.php?t=175063

**Comment by MoritzLoewenstein** [comment]
Yes, you need curl for uploading and bzip only if you use compression. Both these extensions are included in this repository. The plugin supports any ftp server.
