### ISSUE TITLE
@ in username - "Couldn't resolve host name"

### ISSUE THREAD

**Issue by enghausen** [MoritzLoewenstein/AutoDemoUpload#11]
Hi,

I got a FTP server at a provider that uses cPanel. cPanel "link" FTP accounts to domains which result in FTP usernames with @ like ftpuser@domain.com

This means we end up with an URL like:
`"ftp://ftpuser@domain.com:password@domain.com:21/files"`

Now cURL think domain.com is the domain and giving me the "Couldn't resolve host name" error.

If you make a password with @ you would end up with the same result.

**Any chance you have played a round with this error before?**

I tried URL Encoding (@ as %40), adding some quotes and looked into other options like [CURLOPT_USERNAME](https://curl.se/libcurl/c/CURLOPT_USERNAME.html), but with no luck.

Best regards,

**Comment by enghausen** [comment]
After some more testing the %40 as @ works!

So just use username  like `ftpuser%40domain.com`

The error was that my username ended up being 34 characters long so a `decl String:sUser[64];` could fix it for me (or just use a shorter username.

**Comment by MoritzLoewenstein** [comment]
Thanks for figuring it out, fixed it.
