### ISSUE TITLE
SSL connect error

### ISSUE THREAD

**Issue by breezetix** [MoritzLoewenstein/AutoDemoUpload#12]
not sure if it's related to this plugin at all but L 07/02/2022 - 01:07:06: [tEasyFTP.smx] Failed uploading /demos/auto-20220702-010432-de_mirage.dem.bz2 (SSL connect error).

**Comment by MoritzLoewenstein** [comment]
What is your "ssl" value in RemoteTargets.cfg?

**Comment by breezetix** [comment]
changed it to "none" and it finally works, it was "try"

**Comment by breezetix** [comment]
should add a note on your plugin to let people know if it doesn't work they should try "none"

**Comment by breezetix** [comment]
also do you know what could cause this? L 07/23/2022 - 10:46:28: [tAutoDemoUpload.smx] bzip2 Error: BZ_IO_ERROR_INPUT

sm_tautodemoupload_bzip2 "1"

i had it on 9, now 1, i'd ahve to turn it off for the errors to stop

**Comment by MoritzLoewenstein** [comment]
You can try the command without quotes, but not sure if it will make a difference.
