### ISSUE TITLE
fix discord demo links or maps not matching

### ISSUE THREAD

**Issue by ghost** [MoritzLoewenstein/AutoDemoUpload#14]
![image](https://user-images.githubusercontent.com/54699547/181843216-b8f48b04-122f-4a82-937e-f6b85553c740.png)

**Comment by MasterWindowS** [comment]
I fix that
Discord: ShadowSpecter#2387

**Comment by MoritzLoewenstein** [comment]
Please consider submitting your fix as a PR @MasterWindowS

**Comment by MasterWindowS** [comment]
It's quite simple, I created an array where the played maps are saved (in this case the last map), and then I showed it in the translation

![image](https://user-images.githubusercontent.com/71204342/213168516-fa70988f-d903-4c95-92bd-a373053b817d.png)

**Comment by MasterWindowS** [comment]
![image](https://user-images.githubusercontent.com/71204342/213176531-992f86e5-4426-474d-8147-9c8a4fa20d8f.png)
![image](https://user-images.githubusercontent.com/71204342/213176568-4db4a72d-305a-4f23-a123-32d775341671.png)
![image](https://user-images.githubusercontent.com/71204342/213176636-f258384c-efbd-43fb-bef9-b001adcdba5e.png)
![image](https://user-images.githubusercontent.com/71204342/213176675-3e690be8-caba-40ca-9d61-e4f88727ddbe.png)

**Comment by MasterWindowS** [comment]
It should be said that this is a test, and I continue to test that it works. But for the moment everything has been working correctly.
