### ISSUE TITLE
warmod - folder

### ISSUE THREAD

**Issue by MikkelDK** [MoritzLoewenstein/AutoDemoUpload#2]
Hi,

Is it possible for, it can upload demos from the (warmod) folder?

Example:
csgo/warmod/.dem files will be here.

But they will not be uploaded.
Only if using: Get5/Pugsetup/eBot = works fine.
If using warmod = no demo will be uploaded (no error - just completed demo and no upload)

**Comment by MoritzLoewenstein** [comment]
Sorry for the late answer, i only got the notification when you closed the issue. Is this still a problem or did you fix it?

**Comment by MikkelDK** [comment]
Yeah! =) I did solve it.

**Comment by MoritzLoewenstein** [comment]
I will add the local demo path as cvar tomorrow, i guess you did the same

**Comment by crashzk** [comment]
@mrc4tt sorry for the ping on a very old issues.

I saw that you managed to solve the upload problem, in the case I have the same, it uploads but there is no way for me to download.

Open an issues here: https://github.com/MoritzLoewenstein/AutoDemoUpload/issues/20

Anyway, could you help me with how to fix it? I use WarMod [BFG] too.
