### ISSUE TITLE
[Request] Sending Message to Discord.

### ISSUE THREAD

**Issue by MikkelDK** [MoritzLoewenstein/AutoDemoUpload#3]
Hi,

It could be nice if it's possible to make;

So example this:
```
public UploadComplete(const String:sTarget[], const String:sLocalFile[], const String:sRemoteFile[], iErrorCode, any:data) {
	if(iErrorCode == 0 && g_bDelete) {
		DeleteFile(sLocalFile);
		if(StrEqual(sLocalFile[strlen(sLocalFile)-4], ".bz2")) {
			new String:sLocalNoCompressFile[PLATFORM_MAX_PATH];
			strcopy(sLocalNoCompressFile, strlen(sLocalFile)-3, sLocalFile);
			DeleteFile(sLocalNoCompressFile);
		}
	}

	if(iErrorCode == 0) PrintToChatAll("[SourceTV] Demo uploaded successfully")`
```

So it's possible to make a little plugin, so it will "chat" to specific room on Discord, with this text: 
"[SourceTV] Demo uploaded successfully" - without its need to post in-game of the gameserver.

**Do you think it's possible? - if we can talk about it, about I can contact you private with a little offer cash?**

**Comment by MikkelDK** [comment]
@MoritzLoewenstein ^^ I hope you're getting the message now, without I need to close again :D

**Comment by MoritzLoewenstein** [comment]
Yes, this is possible, I already did this for a few discord servers. You need to create a webhook in the channel and use sourcemod_discord (on my github).

**Comment by MikkelDK** [comment]
Is it possible, to make.. so it's work for diff discord servers + which channel it should post message per .cfg file? or do I need to edit the .sp file for each discord server?

**Comment by MikkelDK** [comment]
@MoritzLoewenstein 

so I need to place it, like this?

```
public UploadComplete(const String:sTarget[], const String:sLocalFile[], const String:sRemoteFile[], iErrorCode, any:data) {
	if(iErrorCode == 0 && g_bDelete) {
		DeleteFile(sLocalFile);
		if(StrEqual(sLocalFile[strlen(sLocalFile)-4], ".bz2")) {
			new String:sLocalNoCompressFile[PLATFORM_MAX_PATH];
			strcopy(sLocalNoCompressFile, strlen(sLocalFile)-3, sLocalFile);
			DeleteFile(sLocalNoCompressFile);
		}
	}

	if(iErrorCode == 0) PrintToChatAll("[SourceTV] Demo uploaded successfully")`
Discord_SendMessage(DISCORD_WEBHOOK, or somehow.
```

I'm not expert with scripting! =) so that's why I offer $ via PayPal!

**Comment by MoritzLoewenstein** [comment]
You want just the "upload completed" message or also the download link? I dont do paypal work but maybe I can put it up on github for everyone since a few people asked me about this.

**Comment by MikkelDK** [comment]
Both will be much nice. =)

**Comment by MikkelDK** [comment]
Both. message + download link. =) 

It could be pretty nice.
- It could be much nice, if it's possible to make, so I can "typo" webhook URL by cfg file. =) without to compile "for each" gameserver. I have around 20 CSGO Servers atm =D

Let me know, once it's fixed! =D
@MoritzLoewenstein

**Comment by MoritzLoewenstein** [comment]
It should be possible now, you have to set these two options:  
`sm_teasyftp_discord_webhook <your_discord_webhook>`  
`sm_teasyftp_announce_on_discord 1`
ping @MikkelDK

**Comment by MikkelDK** [comment]
I will check! ;)

**Comment by MikkelDK** [comment]
@MoritzLoewenstein 

Do I need to use https?
Seems I getting this:
```
] rcon sm_teasyftp_discord_webhook
"sm_teasyftp_discord_webhook" = "https:" ( def. "" ) 
```

**Comment by MoritzLoewenstein** [comment]
You can have different directories for each server (on the upload server) and then you see it in the download url, or you can make different channels and use a different webhook url for each server.  
Maybe I will add an option.

**Comment by MikkelDK** [comment]
@MoritzLoewenstein Thank you for your help! =)

I was thinking, about it's possible the "Format" can understand "Hostname" field from server.cfg

```
Format(sDownloadURL, sizeof(sDownloadURL), "%hostname% - Map: %s Download: http://%s", sCurrentMap, sDownloadURL);
```
So its output: 
**MikkelDK Server - Map: de_dust2 >> Download: http://mikkeldk.blabla.org/demo.dem**

**Comment by MoritzLoewenstein** [comment]
If you change something in this file it will not change anything, maybe I will add this option.

**Comment by MikkelDK** [comment]
> If you change something in this file it will not change anything, maybe I will add this option.

@MoritzLoewenstein 
I did try this: - without response!
```
decl String:ServerName[64];
				new Handle:convar = FindConVar("hostname");
				GetConVarString( convar, ServerName, sizeof(ServerName)); 
				Format(sFtpURL, sizeof(sFtpURL), "ftp://%s:%s@%s:%i%s%s", sUser, sPassword, sHost, iPort, sForcePath, sRemoteFile);
				Format(sDownloadURL, sizeof(sDownloadURL), "%s/%s%s%s", sHost, sUser, sForcePath, sRemoteFile);
				if (GetConVarBool(g_hCvarAnnounceOnDiscord)) {
					GetConVarString(g_hCvarDiscordWebhook, g_sDiscordWebhook, sizeof(g_sDiscordWebhook));
					GetCurrentMap(sCurrentMap, sizeof(sCurrentMap));
					Format(ServerName, sizeof(ServerName), sDownloadURL, sizeof(sDownloadURL), "%s - Map: %s >> Download: http://%s ", ServerName, sCurrentMap, sDownloadURL);
					Discord_SendMessage(g_sDiscordWebhook, sDownloadURL);
				}
```

**Comment by MoritzLoewenstein** [comment]
as i said, it doesnt make any difference if you change something in this file.
to format the message the way you want use:
`sm_teasyftp_announce_format "%host - Map: %map >> Download: %dl_url"`

**Comment by MikkelDK** [comment]
> as i said, it doesnt make any difference if you change something in this file.
> to format the message the way you want, use:
> `sm_teasyftp_announce_format "%host - Map: %map >> Download: %dl_url"`

Little error:
It doesn't incl http://

![](https://pic.lindhost.eu/Discord_UMTFhlT6lj.png)

**Comment by MoritzLoewenstein** [comment]
fixed, gn8

**Comment by MikkelDK** [comment]
Hey @MoritzLoewenstein 
Is it possible for so I can remove the "User" of the DL_URL?

**It should look like this:**
http://some.domain.TLD/demofilehere.dem **//This need!**

**It DON'T need to be**:
http://some.domain.TLD/some/demofilehere.dem

**Comment by MoritzLoewenstein** [comment]
stop replying to closed issues.
user is required because your ftp host needs to know which user account the file is in.
