### ISSUE TITLE
Update on the Plugin Discord API

### ISSUE THREAD

**Issue by crashzk** [MoritzLoewenstein/AutoDemoUpload#4]
I wonder if I could update the Plugin Discord API to this version: https://github.com/Deathknife/sourcemod-discord/blob/master/discord_api.sp

I think it has more resources so I could see analyzing both codes.

https://github.com/Deathknife/sourcemod-discord

Would it be possible to implement this version in AutoDemoUpload?

**Comment by MoritzLoewenstein** [comment]
There is a difference between a webhook and an discord bot. My plugin is only sending messages with the webhook, a discord bot has a lot more capabilities which this plugin currently doesnt need.
We could implement [this](https://github.com/Deathknife/sourcemod-discord/blob/master/discord/SendWebHook.sp) into AutoDemoUpload, it offers a lot more customization of the message (embed etc).
What do you want to do that is currently not possible?

**Comment by crashzk** [comment]
I understand, is that there is a plugin that uses that version: https://forums.alliedmods.net/showthread.php?p=2629494

In case he doesn't use BOT, only WebHook also to send the information on Discord.

In the case I suggested this change that more customization can be given in the messages that AutoDemoUpload sends on Discord, leave behind in this format, instead of a simple message, embed format I believe:
![image] (https://user-images.githubusercontent.com/32937653/83976311-aea58080-a8cf-11ea-9eb2-829fa5c22061.png)

Anyway, it could include in addition to sending messages with this information:

- %map
- %dl_url
- %host

From what I could see, Host sends the name of the server, correct? Or is it the IP?

Anyway, in addition to these options Also include the server name, server IP.

Would these changes be possible?

**Comment by MoritzLoewenstein** [comment]
Yes, this picture is an embed. Since I dont want to make the configuration too complicated I will only offer extended format (similar to the picture) and message format like it is now.  
`%host` is the normal server hostname (`[SNG] 24/7 Jailbreak | !knife !ws | Last CT` in image).
Instead of `Quick Join` will be download url & I dont think we need `Players online`.

**Comment by crashzk** [comment]
I understand, yes `Payers Online` need not.

Anyway, thanks for the explanations, I will be testing thoroughly, anything I will contact you again.

**Comment by MoritzLoewenstein** [comment]
Maybe I have time to add it this evening, worst case it will be finished on the weekend.
