### ISSUE TITLE
Demos not Uploading To Web Server

### ISSUE THREAD

**Issue by Shaneajm** [MoritzLoewenstein/AutoDemoUpload#5]
The plugin isn't stopping demos until the map change so they never get uploaded. I ran `tv_stoprecord` and the demo completes and sends the message for the demo. An easy fix, I'll just get/make a plugin that stops it for me on map end.

The issue now is that the plugin is appending /gotv at the end of my URL. So instead of uploading to `gotv.example.com/Retakes3` as set in the `RemoteTargets.cfg` it's sending the URL in chat as `gotv.example.com/gotv/Retakes3`. I created a folder called gotv on the web server as a temporary fix and moved everything into it but I'm still getting this error in the log now.

> L 09/09/2020 - 14:32:01: [tAutoDemoUpload.smx] C:\servers\csla2\csgo\auto-20200909-1430-de_mirage.dem compressed to auto-20200909-1430-de_mirage.dem.bz2
L 09/09/2020 - 14:32:01: [tEasyFTP.smx] Uploading file auto-20200909-1430-de_mirage.dem.bz2 (356251 byte) to target demos
L 09/09/2020 - 14:32:01: [tAutoDemoUpload.smx] demo upload errorcode: 6
L 09/09/2020 - 14:32:01: [tEasyFTP.smx] Failed uploading auto-20200909-1430-de_mirage.dem.bz2 (Couldn't resolve host name).

Here is my `RemoteTargets.cfg` (with domain removed) if this helps:

```
 "RemoteTargets"
{
	"demos"
	{
		"host"		"gotv.example.com"
		"port"		"22"
		"user"		"gotv"
		"password"	"password"
		"path"		"/Retakes3"
		"ssl"		"try"
		"CreateMissingDirs"	"1"
	}
}
```

**Comment by Shaneajm** [comment]
Alright so I found part of the problem. The plugin isn't stopping demos until the map change so they never get uploaded. I ran `tv_stoprecord` and the demo completes and sends the message for the demo. The issue now is that the plugin is appending /gotv at the end of my URL. So instead of uploading to `gotv.example.com/Retakes3` as set in the `RemoteTargets.cfg` it's sending the URL in chat as `gotv.example.com/gotv/Retakes3`. I created a folder called gotv on the web server as a temporary fix and moved everything into it but I'm still getting this error in the log now.

> L 09/09/2020 - 14:32:01: [tAutoDemoUpload.smx] C:\servers\csla2\csgo\auto-20200909-1430-de_mirage.dem compressed to auto-20200909-1430-de_mirage.dem.bz2
L 09/09/2020 - 14:32:01: [tEasyFTP.smx] Uploading file auto-20200909-1430-de_mirage.dem.bz2 (356251 byte) to target demos
L 09/09/2020 - 14:32:01: [tAutoDemoUpload.smx] demo upload errorcode: 6
L 09/09/2020 - 14:32:01: [tEasyFTP.smx] Failed uploading auto-20200909-1430-de_mirage.dem.bz2 (Couldn't resolve host name).

Here is my `RemoteTargets.cfg` if this helps:

```
 "RemoteTargets"
{
	"demos"
	{
		"host"		"gotv.example.com"
		"port"		"22"
		"user"		"gotv"
		"password"	"password"
		"path"		"/Retakes3"
		"ssl"		"try"
		"CreateMissingDirs"	"1"
	}
}
```

**Comment by MoritzLoewenstein** [comment]
In general, the plugin is not intended to start/stop demos at all, it is just used to upload all demos which are recorded (it listens to the stop demo command). At map change any demo recording will automatically end.

If I understand correctly:
1. the plugin isnt uploading any demos at all (because of unresolvable hostname even though it should be correct)
2. its posting the wrong download link in chat

The default format for the upload url is: `ftp://user:password@host:port/path/filename`
I assume with your hosting provider it should be: `ftp://user:password@user.host:port/path/filename` (can you confirm this?)
The default format for the download url is: `http://host/user/path/filename`
In your case it should be: `http://user.host//path/filename`, tell me if I am wrong.
Before I start to change anything, can you try out `example.com` as host?

**Comment by Shaneajm** [comment]
First, I realized I was dumb and trying to upload to a web directory. I created a brand new SFTP server using vsftpd and made the directories, etc. 

I updated my information in the RemoteTargets as follows:
```
"RemoteTargets"
{
	"demos"
	{
		"host"		"gotv.mydomain.com"
		"port"		"22"
		"user"		"sftpuser"
		"password"	"passwordlol"
		"path"		"/sftpgotv/Retakes3"
		"ssl"		"try"
		"CreateMissingDirs"	"1"
	}
}
```

Now when the demo completes I get this as an error:
```
L 09/10/2020 - 12:55:58: [tAutoDemoUpload.smx] demo upload errorcode: 28
L 09/10/2020 - 12:55:58: [tEasyFTP.smx] Failed uploading auto-20200910-1253-de_mirage.dem.bz2 (Timeout was reached).
```

**Comment by MoritzLoewenstein** [comment]
I think the issue is sftp, the uploader only supports ftp & ftp over ssl (denpending on ssl setting) as far as i know.
