### ISSUE TITLE
URL from dathost not working.

### ISSUE THREAD

**Issue by br4mSuurd** [MoritzLoewenstein/AutoDemoUpload#9]
everytime the game ends and the oposing team pastes the link in their browser. it just sends them to the dathost website. am i just being stupid or did i so something wrong?

```
"RemoteTargets"
{
	"demos"
	{
		"host"		"olly.dathost.net"
		"port"		"21"
		"user"		"61be2291e9d80514699d6ff0"
		"password"	"-"
		"path"		"/demos/"
		"ssl"		"try"
		"CreateMissingDirs"	"1"
	}
}
```

here's my RemoteTargets.cfg with the password being removed

`de_mirage: http://olly.dathost.net/61be2291e9d80514699d6ff0/demos/2022-01-30_18-21_de_mirage.dem.bz2`
this is an example of the link that i get after the game ends. when i paste that in my browser i just get send to the dathost website.

any way to fix this?

**Comment by br4mSuurd** [comment]
and also, im quite new to editing server files. so where do i add the discord intergration commands to?

**Comment by MoritzLoewenstein** [comment]
configuration looks fine to me, you will have to figure out how a public link to a file on dathost looks like. I added some changes to this plugin which will allow you to change the link (because its not always the same).
You can add the discord configuration commands to your server.cfg.

**Comment by MoritzLoewenstein** [comment]
You can use `"dl_url"	"http://example.org/your/path"` in your RemoteTargets.cfg, the plugin will just append the demoname.
Closing this.
